// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyoheciyzizvkczwtaoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5b2hlY2l5eml6dmtjend0YW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwOTUxNDcsImV4cCI6MjA2NDY3MTE0N30.YI-w19-GyaOYCMXh-X5R7zTSiVaZMnN0vp12-ecftfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);